/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as ApiAdminParseWechatRouteImport } from './routes/api/admin/parse-wechat'
import { Route as ApiAdminParseMarkdownRouteImport } from './routes/api/admin/parse-markdown'
import { Route as ApiAdminParseImageRouteImport } from './routes/api/admin/parse-image'
import { Route as ApiAdminImportRouteImport } from './routes/api/admin/import'
import { Route as ApiAdminDocumentsRouteImport } from './routes/api/admin/documents'
import { Route as ApiAdminDocumentsIdRouteImport } from './routes/api/admin/documents/$id'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminParseWechatRoute = ApiAdminParseWechatRouteImport.update({
  id: '/api/admin/parse-wechat',
  path: '/api/admin/parse-wechat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminParseMarkdownRoute = ApiAdminParseMarkdownRouteImport.update({
  id: '/api/admin/parse-markdown',
  path: '/api/admin/parse-markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminParseImageRoute = ApiAdminParseImageRouteImport.update({
  id: '/api/admin/parse-image',
  path: '/api/admin/parse-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportRoute = ApiAdminImportRouteImport.update({
  id: '/api/admin/import',
  path: '/api/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocumentsRoute = ApiAdminDocumentsRouteImport.update({
  id: '/api/admin/documents',
  path: '/api/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocumentsIdRoute = ApiAdminDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRouteWithChildren
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/parse-image': typeof ApiAdminParseImageRoute
  '/api/admin/parse-markdown': typeof ApiAdminParseMarkdownRoute
  '/api/admin/parse-wechat': typeof ApiAdminParseWechatRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRouteWithChildren
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/parse-image': typeof ApiAdminParseImageRoute
  '/api/admin/parse-markdown': typeof ApiAdminParseMarkdownRoute
  '/api/admin/parse-wechat': typeof ApiAdminParseWechatRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import': typeof AdminImportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRouteWithChildren
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/parse-image': typeof ApiAdminParseImageRoute
  '/api/admin/parse-markdown': typeof ApiAdminParseMarkdownRoute
  '/api/admin/parse-wechat': typeof ApiAdminParseWechatRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/admin/documents'
    | '/admin/import'
    | '/api/chat'
    | '/api/admin/documents'
    | '/api/admin/import'
    | '/api/admin/parse-image'
    | '/api/admin/parse-markdown'
    | '/api/admin/parse-wechat'
    | '/api/admin/documents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/admin/documents'
    | '/admin/import'
    | '/api/chat'
    | '/api/admin/documents'
    | '/api/admin/import'
    | '/api/admin/parse-image'
    | '/api/admin/parse-markdown'
    | '/api/admin/parse-wechat'
    | '/api/admin/documents/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/admin/documents'
    | '/admin/import'
    | '/api/chat'
    | '/api/admin/documents'
    | '/api/admin/import'
    | '/api/admin/parse-image'
    | '/api/admin/parse-markdown'
    | '/api/admin/parse-wechat'
    | '/api/admin/documents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminImportRoute: typeof AdminImportRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAdminDocumentsRoute: typeof ApiAdminDocumentsRouteWithChildren
  ApiAdminImportRoute: typeof ApiAdminImportRoute
  ApiAdminParseImageRoute: typeof ApiAdminParseImageRoute
  ApiAdminParseMarkdownRoute: typeof ApiAdminParseMarkdownRoute
  ApiAdminParseWechatRoute: typeof ApiAdminParseWechatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/parse-wechat': {
      id: '/api/admin/parse-wechat'
      path: '/api/admin/parse-wechat'
      fullPath: '/api/admin/parse-wechat'
      preLoaderRoute: typeof ApiAdminParseWechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/parse-markdown': {
      id: '/api/admin/parse-markdown'
      path: '/api/admin/parse-markdown'
      fullPath: '/api/admin/parse-markdown'
      preLoaderRoute: typeof ApiAdminParseMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/parse-image': {
      id: '/api/admin/parse-image'
      path: '/api/admin/parse-image'
      fullPath: '/api/admin/parse-image'
      preLoaderRoute: typeof ApiAdminParseImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import': {
      id: '/api/admin/import'
      path: '/api/admin/import'
      fullPath: '/api/admin/import'
      preLoaderRoute: typeof ApiAdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/documents': {
      id: '/api/admin/documents'
      path: '/api/admin/documents'
      fullPath: '/api/admin/documents'
      preLoaderRoute: typeof ApiAdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/documents/$id': {
      id: '/api/admin/documents/$id'
      path: '/$id'
      fullPath: '/api/admin/documents/$id'
      preLoaderRoute: typeof ApiAdminDocumentsIdRouteImport
      parentRoute: typeof ApiAdminDocumentsRoute
    }
  }
}

interface ApiAdminDocumentsRouteChildren {
  ApiAdminDocumentsIdRoute: typeof ApiAdminDocumentsIdRoute
}

const ApiAdminDocumentsRouteChildren: ApiAdminDocumentsRouteChildren = {
  ApiAdminDocumentsIdRoute: ApiAdminDocumentsIdRoute,
}

const ApiAdminDocumentsRouteWithChildren =
  ApiAdminDocumentsRoute._addFileChildren(ApiAdminDocumentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminImportRoute: AdminImportRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAdminDocumentsRoute: ApiAdminDocumentsRouteWithChildren,
  ApiAdminImportRoute: ApiAdminImportRoute,
  ApiAdminParseImageRoute: ApiAdminParseImageRoute,
  ApiAdminParseMarkdownRoute: ApiAdminParseMarkdownRoute,
  ApiAdminParseWechatRoute: ApiAdminParseWechatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
